version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: trytofindme
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  app:
    build: ./app
    restart: always
    ports:
      - 8091:3000

  server:
    build: ./server
    restart: always
    ports:
      - 8092:3000
