version: "3.1"

services:
  db_prod:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: trytofindme
    volumes:
      - ./db/db_prod:/var/lib/postgresql/data

  adminer_prod:
    image: adminer
    restart: always
    ports:
      - 8070:8080

  app_prod:
    build:
        context: ./app
        dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 8071:3000

  server_prod:
    build:
        context: ./server
        dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 8072:3000
