version: "3.1"

services:
  db_dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: trytofindme
    volumes:
      - ./db/db_dev:/var/lib/postgresql/data

  adminer_dev:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  app_dev:
    build:
        context: ./app
        dockerfile: dev.Dockerfile
    restart: always
    ports:
      - 8091:3000

  server_dev: 
    build:
        context: ./server
        dockerfile: dev.Dockerfile
    restart: always
    ports:
      - 8092:3000
